services:
  app:
    container_name: sparkybudget
    env_file:
      - .env
    image: codewithcj/sparkybudget:latest  # Use latest or specific version
    volumes:
      - ./:/private
    ports:
      - 5050:5000  # Update 5050 to your desired port
    restart: unless-stopped
