version: '3'
services:
  app:
    container_name: sparkybudget
    env_file:
      - .env
    image: sparkybudget
    volumes:
      - ./budget:/app      
    ports:
      - 5050:5000
    restart: unless-stopped